# Generated by Django 3.2.5 on 2021-10-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyHall', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelName',
            new_name='PartyHall',
        ),
    ]
